#!/usr/bin/env python3
"""Record real driving loops around Milford for the background cars.

Asks the free OSRM routing server for a handful of round trips between
Milford spots, thins out the points, and writes js/idle-routes.js. The app
reads that file so the idle cars drive on real roads without calling the
routing server on every visit.

Run from the project folder:  python3 tools/bake-idle-routes.py
Only needed again if you want the background cars to use different roads.
"""
import json
import math
import time
import urllib.request
from pathlib import Path

# Each loop is a list of (lat, lng) stops. The route returns to the first stop.
LOOPS = [
    # Village loop: downtown, Kroger, library
    [(42.5919, -83.6005), (42.59372, -83.60415), (42.59012, -83.60915)],
    # Parks loop: Central Park, Hubbell Pond
    [(42.5919, -83.6005), (42.58807, -83.60234), (42.59038, -83.61212)],
    # Main Street north and south
    [(42.5995, -83.6006), (42.5820, -83.6002)],
    # Out to Camp Dearborn
    [(42.5919, -83.6005), (42.58557, -83.62955)],
    # Kensington and Bakers
    [(42.5919, -83.6005), (42.55524, -83.63202), (42.55947, -83.6173)],
    # Up to the high school
    [(42.5919, -83.6005), (42.61689, -83.62375), (42.59372, -83.60415)],
]

OUT = Path(__file__).resolve().parent.parent / "js" / "idle-routes.js"


def meters(a, b):
    r = math.pi / 180
    dlat, dlng = (b[0] - a[0]) * r, (b[1] - a[1]) * r
    h = math.sin(dlat / 2) ** 2 + math.cos(a[0] * r) * math.cos(b[0] * r) * math.sin(dlng / 2) ** 2
    return 2 * 6371008.8 * math.asin(min(1, math.sqrt(h)))


def fetch_loop(stops):
    pts = stops + [stops[0]]
    coords = ";".join(f"{lng:.6f},{lat:.6f}" for lat, lng in pts)
    url = f"https://router.project-osrm.org/route/v1/driving/{coords}?overview=full&geometries=geojson"
    req = urllib.request.Request(url, headers={"User-Agent": "bbuber-bake/1.0"})
    with urllib.request.urlopen(req, timeout=20) as resp:
        data = json.load(resp)
    if data.get("code") != "Ok":
        raise RuntimeError(f"OSRM said {data.get('code')}")
    line = [(round(c[1], 5), round(c[0], 5)) for c in data["routes"][0]["geometry"]["coordinates"]]
    # Drop points closer than 12 m to the last kept point, keep the end.
    kept = [line[0]]
    for p in line[1:-1]:
        if meters(kept[-1], p) >= 12:
            kept.append(p)
    kept.append(line[-1])
    # Close the loop exactly so cars wrap around without a jump.
    if kept[-1] != kept[0]:
        kept.append(kept[0])
    return kept, data["routes"][0]["distance"]


def main():
    loops = []
    for i, stops in enumerate(LOOPS, 1):
        pts, dist = fetch_loop(stops)
        loops.append([[lat, lng] for lat, lng in pts])
        print(f"loop {i}: {len(pts)} points, {dist / 1609.344:.1f} miles")
        time.sleep(1.2)  # be polite to the free server
    body = json.dumps(loops, separators=(",", ":"))
    OUT.write_text(
        "/* Generated by tools/bake-idle-routes.py. Real road loops for the\n"
        "   background cars. Re-run that script to change them. */\n"
        f"window.BBUBER_IDLE_ROUTES = {body};\n"
    )
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
